#!/usr/bin/env bash

cons=$(nmcli con show --active | grep " vpn  " | awk '{print $1}')

case $1 in
  pre)
    for con in $cons; do
      timeout 20 nmcli con down $con
    done
    ;;
  post)
    ;;
esac
