#!/usr/bin/env bash

input="/home/thiago/.remove-select-bluetooth-devices"

if [[ ! -f "$input" ]]; then
  exit 0
fi

$HOME/bin/notify-desktop "Please wait..." "Removing Bluetooth devices..."

case $1 in
  pre)
    while IFS= read -r device
    do
      logger "system-sleep script disconnecting $device"
      bt-device -d "$device"
    done < "$input"
    ;;
  post)
    # Do nothing
    ;;
esac
