#!/bin/bash

dir="$(cd "$(dirname "$0")" && pwd)"
source $dir/helpers.sh

setting_id=$1

[[ -z "$setting_id" ]] && abort "Please specify a dot-separated gsetting"

setting=$(setting_for $setting_id)
contents=$(dconf list $setting 2> /dev/null)

[[ -z "$contents" ]] && abort 'ERROR: Empty key!'

file="$dir/settings/$setting_id"

dconf dump $setting > $file

unwanted_patterns='mru-sources='

if grep "$unwanted_patterns" "$file" > /dev/null; then
  grep -v mru-sources "$file" > "$file.tmp"
  mv "$file.tmp" "$file"
fi
