#!/bin/bash

DIR="$(pwd)/"
SOURCE_DIR=$(dirname $BASH_SOURCE)

if [[ ! -z "$INSIDE_EMACS" ]]; then
    unset GIT_LITERAL_PATHSPECS
    APP=$(basename $SOURCE_DIR)
    emacsclient -e "(tags \"${DIR}/\" \"${APP}\")"
else
    $SOURCE_DIR/ctags >/dev/null 2>&1 &
fi
